name: "bluebell"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760 #JWT过期时间

log:
  level: "debug"
  filename: "bluebell01.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "bluebell"
  max_open_conns: 2000
  max_idle_conns: 100
redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100